### ISSUE TITLE
New Standards not populating in the bottom "available standards" box. 

### ISSUE THREAD

**Issue by pacree** [mmansfield/edCorrelator#1]
I can create a new set of standards (awesome). 
![image](https://cloud.githubusercontent.com/assets/4050932/7494769/b5b80288-f3d7-11e4-8479-4a316c33e4d7.png)

BUT - I can't add the new standards to lessons. I tried filtering the list b/c I didn't see the standards, no dice. 
![image](https://cloud.githubusercontent.com/assets/4050932/7494859/41034ba4-f3d8-11e4-8096-4ce26c626aac.png)

NOTE:  Chris is still working on the UI for this but wanted to get functionality into this release... Might be a 'bug' or might be under development still.

**Comment by chornbe** [comment]
This is fixed. The query for unselected standards was needlessly including the Mapping table and filtering out things that didn't exist with *any* mappings. That was a dumb oversight on my part. -- ch

**Comment by chornbe** [comment]
rolled to dev and prod. This can be closed.

**Comment by pacree** [comment]
now it has add/remove buttons, yay! 
![image](https://cloud.githubusercontent.com/assets/4050932/7539640/50f57286-f576-11e4-8043-ee752cbdb9e9.png)
